### ISSUE TITLE
can not send negative value as geolocation data, gets parsed as argument

### ISSUE THREAD

**Issue by mmajass** [Lora-net/lr1110_evk_demo_app#1]
my geolocation starts with -33 (latitude) however Lr1110Demo thinks i'm trying to send an argument.

tried -- -33 and -s-33 and -extra -33 and "-33" and \-33 but the geolocation does not get parsed.

how to replicate:

Lr1110Demo -33.xxxx,151.xxxx,100 -33.xxxx,151.xxxx,100 <token 1> <token 2> -r -d /dev/tty.usbmodem14603

Expected behaviour: 

geolocation gets parsed correctly

Actual behaviour:

'-' in front of latitude seems to be parsed as token

thanks

**Comment by joeknapp** [comment]
Hi,

Using '--' between the optional flags and the mandatory elements will solve this problem. So, change your command line to:

Lr1110Demo -r -d /dev/tty.usbmodem14603 -- -33.xxxx,151.xxxx,100 -33.xxxx,151.xxxx,100 <token 1> <token 2> 

Fixed?

**Comment by mmajass** [comment]
Fixed, thanks
