### ISSUE TITLE
NAV message payload

### ISSUE THREAD

**Issue by alexisblaya** [Lora-net/lr1110_evk_demo_app#13]
Hi,

I can see in the UserManual_LR1110 documentation and in the LR1110_gnss_types.h file that the payload can integrate several information, including pseudo-ranges. 
Is there a document that explains how the NAV message payload is built, or a way to extract pseudo-ranges from the payload?

Thank you in advance
Alexis

![image](https://user-images.githubusercontent.com/80394427/113837277-f7e38c80-978d-11eb-96f1-e5cc4724e052.png)
![image](https://user-images.githubusercontent.com/80394427/113838137-c8814f80-978e-11eb-8ed5-62e3f69c440a.png)

**Comment by matthieuantoine** [comment]
Hi, the content of the NAV payload is not public.

**Comment by induthings-coder** [comment]
Dear All, any news about NAV message payload... for on-premise solutions... is possible to use RTK library to decode it? Thanks

**Comment by joeknapp** [comment]
Hi, aogonzalez75. As mentioned earlier on this thread, the NAV payload format is proprietary to Semtech and confidential to Semtech. Please contact Semtech Sales for more details and to discuss your on-premise needs.
