### ISSUE TITLE
lr1110_modem test method

### ISSUE THREAD

**Issue by enddls** [Lora-net/lr1110_evk_demo_app#14]
hi,

I have two question.

first, when lr1110 was updated e-modem, how use packet error rate mode ? 

lr1110 updated lr1110_modem_1.1.7.h.

so I try to use packet error rate in lr1110_evk_demo_app.

but packet error rate don't operate.

second, when lr1110 updated e-modem, Can I use lr1110_driver("https://github.com/Lora-net/lr1110_driver")?

if updated e-modem lr1110 can use lr1110_driver, how use lr1110_driver?

thank you.

**Comment by matthieuantoine** [comment]
Here is the firmware / driver combo:
* LoRa Basics Modem-E firmware https://github.com/Lora-net/radio_firmware_images/tree/master/lr1110/modem#driver-version
* LR1110 firmware https://github.com/Lora-net/radio_firmware_images/tree/master/lr1110/transceiver#driver-version
