### ISSUE TITLE
Setup with Keil

### ISSUE THREAD

**Issue by sohaibqamar** [Lora-net/lr1110_evk_demo_app#15]
Hi, 
I am trying to build the app using Keil (version 5.22).
I have the LR1110 Dev Kit with a touch screen LCD.
After cloning the project from the repo, I opened the project in Keil. When I build the project I am getting below errors.

`compiling timer_interface_implementation.cpp...
Fatal error: C3900U: Unrecognized option '-no-deprecated-register'.`

Above Error is for most of the .cpp files and at the end I am getting the below error
`linking...
.\Objects\lr1110_evk.axf: error: L6002U: Could not open file .\objects\main.o: No such file or directory
Finished: 0 information, 0 warning, 0 error and 1 fatal error messages.
".\Objects\lr1110_evk.axf" - 1 Error(s), 0 Warning(s).`

Is there a guide or tutorial for compiling and building this Demo Application, I need to add/remove some features using this code as a base. 
Apologies If it's too trivial as I am just getting started with the development using this kit.
Any help would be really appreciated. 
Regards

**Comment by ardsh07** [comment]
Hi Sohaib, Please check if you have accidently changed "Misc control", for C/C++ set it correctly in the Keil. Project->Options for target 'stm32l476rg' to 

-Wno-deprecated-register

I cloned and compiled with version 5.34.0.0 with no errors.

**Comment by sohaibqamar** [comment]
@ardsh07 Thank you for the response. 

When I set the option to -Wno-deprecated-register
![image](https://user-images.githubusercontent.com/12796461/164873210-1b391236-f1f8-43d2-a842-9a2e891028c7.png)

Below are the Errors I am getting as in the screenshot
![image](https://user-images.githubusercontent.com/12796461/164873312-64500f76-9082-46d8-a223-1cd1c9aed7c7.png)

Above Error is for most of the .C & .CPP files, and in the end I am getting

![image](https://user-images.githubusercontent.com/12796461/164873351-fb614ca2-08f2-4ec2-9d52-ca35551325b0.png)

If I remove -Wno-deprecated-register, then I am getting more than 1100 Errors after Building the project.
Looking for any helpful tips.
Regards

**Comment by ardsh07** [comment]
I see the issue now. You are using ARM compiler 5 (ARMCC). This code compiles with ARM compiler 6 (ARMCLANG). 

Could you please switch to v6? I have tested with compiler v6.16.
*** Using Compiler 'V6.16', folder: 'C:\Keil_v5\ARM\ARMCLANG\Bin'
