### ISSUE TITLE
Increase frequency range on EVK interface

### ISSUE THREAD

**Issue by syedkarim** [Lora-net/lr1110_evk_demo_app#2]
The UI on the EVK limits the input frequency to 999999999 MHz. How can this be changed to allow for bench testing above 1 GHz?

**Comment by syedkarim** [comment]
Is it simply a matter of changing the value on Line 59 after "Frequency (Hz)" from the current 9 to a value of 10?
And then compiling and flash.

**Comment by matthieuantoine** [comment]
The LR1110 is not supposed to work with frequency above 960MHz (see FRRXLF in table 3-12 of the datasheet).

The limit you see is just the maximum number of digits allowed for this parameter. As you suggested, you can increase this maximum number but I do remind that this value is not supported by the chip.
