### ISSUE TITLE
Almanac Update failed

### ISSUE THREAD

**Issue by WinXprt** [Lora-net/lr1110_evk_demo_app#3]
I have tried to update the almanac image that is provided to the LR1110 EVK in GNSS assisted mode.

![issue_almanac_update_fail](https://user-images.githubusercontent.com/32786723/88167221-1fadb700-cc36-11ea-95fb-25a4e73fa7af.png)

I have got the issue as shown in the above. I have tried to reset the STM32 Nucleo board and reconnected that couldn’t solve the issue.

Can anyone help on this?

**Comment by matthieuantoine** [comment]
Can you please share the 2 following info?
- the version of the firmware running in the LR1110
- the version of the EVK demo application running in the STM32

You can get both information through the "About" pages (accessible from the splashscreen).

**Comment by WinXprt** [comment]
a. 0x0302
b. lr1110 evk 1.3.0 software package

**Comment by matthieuantoine** [comment]
Please update your chip to 0x0303 (more information available here: https://github.com/Lora-net/lr1110_evk/wiki/Updater-tool) - it will fix your issue.

**Comment by matthieuantoine** [comment]
Let me know if you still have the issue with the latest firmware.

**Comment by WinXprt** [comment]
@matthieuantoine I am still facing the same issue

![lr1110_evk png](https://user-images.githubusercontent.com/32786723/97193930-8dd2be80-17cf-11eb-8ddc-2ea4ad92422b.jpg)


![Almanac Update failed](https://user-images.githubusercontent.com/32786723/97189876-1569fe80-17cb-11eb-91ac-059b0105de78.png)

**Comment by matthieuantoine** [comment]
Can you please update everything (Python package and Evaluation Kit) to the latest version? You can find it [here](https://github.com/Lora-net/lr1110_evk_demo_app/wiki/files/software-packages/lr1110_evk_demo_app_v2.0.0.zip)

**Comment by WinXprt** [comment]
Okay @matthieuantoine . Will update and check.
