### ISSUE TITLE
Not getting LR1110EVK Device Details via UART Interface

### ISSUE THREAD

**Issue by WinXprt** [Lora-net/lr1110_evk_demo_app#4]
I was trying to get the LR1110 EVK Device details such as DEVEUI, APPEUI, DEVICEPIN in two ways

In the **[LoRa Cloud Device Join Quick start guide](https://www.loracloud.com/documentation/join_service?url=quickstart.html)** it is mentioned that 

1. The device’s EUI and PIN can be found printed on the package.
2. Retrieving from the device  via UART Interface 

I am trying to send the commands mentioned in the user manual via **UART interface**

**UART Configuration:** COM4, 921600, 8, none, 1

**Commands** which I am sending  are 
1. For DEVEUI I have tried with GetDevEUI, GetDevEUI(), and sending Opcode
2. For APPEUI I have tried with GetAppEUI, GetAppEUI(), and sending Opcode
3. For Device pinI have tried with ReadDevicePin , ReadDevicePin(), and sending Opcode

**Result/Observation**

![issue_device_details](https://user-images.githubusercontent.com/32786723/88168997-e460b780-cc38-11ea-99e8-89abe357dbff.png)

**Required information:**

1. Can anyone help on this?
2. Is this the correct way to send commands via UART interface?
3. If not the correct way, what is the correct way to read the data via the UART interface.

**An alternative way which I want to try out is**

1. Calling the API Function which reads the DEVEUI, APPEUI, Device PIN in the application code

**Comment by matthieuantoine** [comment]
The correct way to interact with the EVK is through the Python application available in the delivery - see the readme file (https://github.com/Lora-net/lr1110_evk/blob/master/README.md).

**Comment by WinXprt** [comment]
In the [LoRa Cloud Device Join Quick start guide](https://www.loracloud.com/documentation/join_service?url=quickstart.html) it is mentioned that "Retrieving from the device via UART Interface(Refer Semtech Modem Documentation)". As far I know STM32 communicates with LR1110 via SPI Interface.

* Is Semtech Modem Documentation refers to LR1110 User Manual?

**Comment by matthieuantoine** [comment]
Actually, the EVK communicates with the host computer via Serial-over-USB interface.

In your case, the paragraph you are mentioning refers to another product (a LoRaWAN modem based on a Murata module - https://wireless.murata.com/type-abz-104.html)
