### ISSUE TITLE
GNSS solver error [1]: Not enough viewable satellites

### ISSUE THREAD

**Issue by WinXprt** [Lora-net/lr1110_evk_demo_app#5]
**Test                  :** GNSS Scanning
**Modes tested	:** GNSS Autonomous and Assisted Modes
**Environment	:** Cloudy

![issue_not_enough_satellites_info](https://user-images.githubusercontent.com/32786723/88175984-42df6300-cc44-11ea-86e1-c928ca1aad1c.png)

**Observations:**

1. Got 1-3 satellites found on the LR1110 EVK Display
2. Got Error from Solver: GNSS Solver error [1]: Not enough viewable satellites on the HOST PC.

**Required Information:**

1. Can anyone explain the reason for this behavior? 
2. Any details about that will definitely help us to proceed further

.

**Comment by matthieuantoine** [comment]
This means that the solver cannot determine your position based on the data you sent - in this case, the resolution does not work because there is not enough satellite.

Can you give me more context concerning the way you make this measure?
