### ISSUE TITLE
almanacupdate algorism 

### ISSUE THREAD

**Issue by enddls** [Lora-net/lr1110_evk_demo_app#7]
I am reviewing lr1110 ev-board at lr1110 gnss assisted function.

this function need to almanac.

but I dont know almanac update algorism at lr1110_evk-master and AlmanacUpdate program.

1. I want to know almanac update algorism.

2. I want almanac day check method.

3. do almanac equal GNSS TOKEN?

please help me.

**Comment by matthieuantoine** [comment]
Hi @enddls,

It seems that you are trying to use the GNSS assisted scan and you get an "almanac too old" error.

To update the Almanac, you first need to create an account on https://www.loracloud.com/. Then you can follow the [step-by-step guide](https://www.loracloud.com/documentation/device_management?url=gettingstarted.html) to create the DAS token.

In a second step, you need to install the Python host application following [this guide](https://github.com/Lora-net/lr1110_evk_demo_app#build--install).

Once this token is created and the host application is installed, you can follow the steps described in the [README file](https://github.com/Lora-net/lr1110_evk_demo_app#almanacupdate-usage) to update the almanac on the LR1110.

We did not implement an automatic almanac update on the EVK. You have to do it manually as described above.
