### ISSUE TITLE
Incorrect linking of the readme file page

### ISSUE THREAD

**Issue by WinXprt** [Lora-net/lr1110_evk_demo_app#8]
When I tried to access the dedicated document given in the LR1110 Host software readme -> Install instruction section got page not found.

- [x] Modify the link attached to the dedicated document 
--- from https://github.com/Lora-net/lr1110_evk_demo_app/blob/master/host/host/doc/install_instructions.md 
++ to https://github.com/Lora-net/lr1110_evk_demo_app/blob/master/host/doc/install_instructions.md

**Comment by matthieuantoine** [comment]
Thanks for reporting this inconsistency - it will be fixed in the next release.

**Comment by WinXprt** [comment]
@matthieuantoine I hope this inconsistency is not yet fixed in the latest release.

**Comment by matthieuantoine** [comment]
> 
> 
> @matthieuantoine I hope this inconsistency is not yet fixed in the latest release.

You're right - we forgot to merge the change in this release. Will be done in the next one.

**Comment by WinXprt** [comment]
> Thanks for reporting this inconsistency - it will be fixed in the next release.

**Comment by matthieuantoine** [comment]
Fixed in v2.2.0
